artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  train_source_url: http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_HR.zip
  valid_source_url: http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_valid_HR.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  train_source_dir: artifacts/data_ingestion/DIV2K_train_HR
  valid_source_dir: artifacts/data_ingestion/DIV2K_valid_HR

model:
  root_dir: artifacts/model
  model_path: arartifacts/model/model.pth
  