ARTIFACTS_ROOT: artifacts

DATA_INGESTION:
  ROOT_DIR: artifacts/data
  TRAIN_SOURCE_URL: http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_HR.zip
  VALID_SOURCE_URL: http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_valid_HR.zip

DATA:
  TRAIN_SOURCE_DIR: artifacts/data/DIV2K_train_HR
  VALID_SOURCE_DIR: artifacts/data/DIV2K_valid_HR
  CROP_SIZE: 256
  DOWN_SCALE: 4

  
MODEL:
  ROOT_DIR: models
  MODEL_PATH: models/model.pth
  NUM_BLOCKS: 6
  SCALE_FACTOR: 4
  LR: 0.001
  DEVICE: cuda
  BATCH_SIZE: 16
  EPOCHS: 50

